# Generated by Django 5.2.4 on 2025-07-10 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='new',
            name='author',
            field=models.CharField(default='', max_length=100, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='new',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='new',
            name='facebook_link',
            field=models.URLField(blank=True, verbose_name='facebook link'),
        ),
        migrations.AlterField(
            model_name='new',
            name='linkedin_link',
            field=models.URLField(blank=True, verbose_name='linkedin link'),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('inprogress', 'In Progress'), ('published', 'Published')], default='Draft', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='new',
            name='twitter_link',
            field=models.URLField(blank=True, verbose_name='twitter link'),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
    ]
