# Generated by Django 5.2.4 on 2025-07-10 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
