# Generated by Django 5.2.4 on 2025-07-10 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_new_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
    ]
