# Generated by Django 5.2.4 on 2025-07-10 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_new_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
