news_data = [
    {
        "title": "Django 5.0 Released with Exciting Features",
        "author": "Alice Johnson",
        "facebook_link": "https://facebook.com/django-news-1",
        "twitter_link": "https://twitter.com/django-news-1",
        "linkedin_link": "https://linkedin.com/in/django-news-1",
        "content": "The Django community has announced version 5.0 with enhanced async support.",
        "status": "published",
    },
    {
        "title": "AI Generates News at Scale",
        "author": "Bob Smith",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "Machine learning models are now used to auto-write news content across industries.",
        "status": "inprogress",
    },
    {
        "title": "Cybersecurity in 2025",
        "author": "Carol White",
        "facebook_link": "https://facebook.com/cyber-2025",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/cyber-2025",
        "content": "Experts warn about quantum threats and push for post-quantum cryptography.",
        "status": "draft",
    },
    {
        "title": "Python Named Top Language Again",
        "author": "David Lin",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/python-top",
        "linkedin_link": "",
        "content": "Python continues to dominate StackOverflow and GitHub statistics.",
        "status": "published",
    },
    {
        "title": "Remote Work Trends in Tech",
        "author": "Evelyn King",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "Major tech firms adopt hybrid and remote-first policies in 2025.",
        "status": "published",
    },
    {
        "title": "Blockchain Beyond Crypto",
        "author": "Frank Zhang",
        "facebook_link": "https://facebook.com/blockchain-news",
        "twitter_link": "https://twitter.com/blockchain-news",
        "linkedin_link": "",
        "content": "Companies now use blockchain for logistics, voting, and identity verification.",
        "status": "inprogress",
    },
    {
        "title": "Frontend Framework Wars Continue",
        "author": "Grace Kim",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "React, Vue, and Svelte continue to evolve rapidly.",
        "status": "draft",
    },
    {
        "title": "Open Source in Government",
        "author": "Henry Patel",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/open-gov",
        "linkedin_link": "https://linkedin.com/in/open-gov",
        "content": "Governments worldwide are adopting open source software to reduce costs.",
        "status": "published",
    },
    {
        "title": "Quantum Computing Breakthroughs",
        "author": "Isabel Gomez",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/quantum-news",
        "content": "New hardware from major players achieves unprecedented coherence times.",
        "status": "inprogress",
    },
    {
        "title": "Green Tech Startups on the Rise",
        "author": "Jason Lee",
        "facebook_link": "https://facebook.com/green-tech",
        "twitter_link": "https://twitter.com/green-tech",
        "linkedin_link": "",
        "content": "Environmental innovation fuels a new wave of investment in green startups.",
        "status": "published",
    },
{
        "title": "New Legislation Targets Big Tech",
        "author": "Karen Davis",
        "facebook_link": "https://facebook.com/tech-legislation",
        "twitter_link": "https://twitter.com/tech-legislation",
        "linkedin_link": "",
        "content": "Lawmakers introduce regulations to increase transparency in tech giants.",
        "status": "draft",
    },
    {
        "title": "5G Expansion Reaches Rural Areas",
        "author": "Leo Carter",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/5g-rural",
        "content": "Telecoms ramp up infrastructure to bring high-speed connectivity to underserved regions.",
        "status": "published",
    },
    {
        "title": "Augmented Reality Goes Mainstream",
        "author": "Maria Ivanova",
        "facebook_link": "https://facebook.com/ar-news",
        "twitter_link": "https://twitter.com/ar-news",
        "linkedin_link": "https://linkedin.com/in/ar-news",
        "content": "AR applications are now common in education, retail, and remote collaboration.",
        "status": "published",
    },
    {
        "title": "Tech Giants Pledge Carbon Neutrality",
        "author": "Nathan Brooks",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "Companies like Google and Apple aim for zero emissions by 2030.",
        "status": "inprogress",
    },
    {
        "title": "Dark Web Markets See Crackdown",
        "author": "Olivia Chen",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/cyber-crime",
        "linkedin_link": "",
        "content": "International task forces shut down multiple illegal online marketplaces.",
        "status": "draft",
    },
    {
        "title": "Developers Prefer TypeScript Over JavaScript",
        "author": "Paul Nguyen",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/ts-trends",
        "linkedin_link": "",
        "content": "Recent surveys show a shift towards TypeScript in major frontend projects.",
        "status": "published",
    },
    {
        "title": "Biometric Data Raises Privacy Concerns",
        "author": "Quinn Russell",
        "facebook_link": "https://facebook.com/privacy-alerts",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "As biometrics become widespread, experts warn of risks in data handling.",
        "status": "inprogress",
    },
    {
        "title": "Startups Innovate in Mental Health Tech",
        "author": "Rita Fernandes",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/mentaltech",
        "linkedin_link": "https://linkedin.com/in/mentaltech",
        "content": "Digital tools and AI are being used to support mental health treatment.",
        "status": "published",
    },
    {
        "title": "European Union Bans Single-Use Plastics",
        "author": "Sophie Müller",
        "facebook_link": "https://facebook.com/eu-environment",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "The EU implements sweeping environmental reforms aimed at plastic waste.",
        "status": "published",
    },
    {
        "title": "Robotic Process Automation Gains Ground",
        "author": "Tomás Rivera",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/rpa-news",
        "content": "Enterprises turn to RPA to streamline back-office operations and cut costs.",
        "status": "inprogress",
    },
    {
        "title": "Data Breach Affects Millions Worldwide",
        "author": "Uma Singh",
        "facebook_link": "https://facebook.com/data-breach",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/cyber-report",
        "content": "A massive data breach has compromised user information across multiple platforms.",
        "status": "published",
    },
    {
        "title": "Space Tourism Industry Gains Momentum",
        "author": "Victor Chang",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/space-news",
        "linkedin_link": "",
        "content": "Private spaceflight companies report increased demand for orbital trips.",
        "status": "inprogress",
    },
    {
        "title": "Education Platforms Embrace AI Tutors",
        "author": "Wendy Adams",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/edtech-ai",
        "content": "AI-powered learning assistants are transforming the way students study.",
        "status": "published",
    },
    {
        "title": "E-Commerce Surges in Developing Countries",
        "author": "Xiao Li",
        "facebook_link": "https://facebook.com/ecommerce-trends",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "Mobile commerce is growing rapidly in Africa, South Asia, and Latin America.",
        "status": "draft",
    },
    {
        "title": "Self-Driving Cars Hit Regulatory Roadblocks",
        "author": "Yasmin El-Sayed",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/autonomous-news",
        "linkedin_link": "https://linkedin.com/in/auto-law",
        "content": "Governments are slow to approve full autonomy amid safety concerns.",
        "status": "inprogress",
    },
    {
        "title": "TikTok Rival Emerges with Focus on Privacy",
        "author": "Zane Roberts",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "A new short-video app promises end-to-end encryption and zero tracking.",
        "status": "draft",
    },
    {
        "title": "Ocean Cleanup Projects Expand Globally",
        "author": "Anna Torres",
        "facebook_link": "https://facebook.com/ocean-cleanup",
        "twitter_link": "https://twitter.com/ocean-news",
        "linkedin_link": "",
        "content": "Innovative solutions are deployed to remove plastic waste from oceans.",
        "status": "published",
    },
    {
        "title": "Tech Salaries Continue to Climb in 2025",
        "author": "Ben Alvarez",
        "facebook_link": "",
        "twitter_link": "",
        "linkedin_link": "",
        "content": "Software engineers and AI researchers see record-high compensation packages.",
        "status": "published",
    },
    {
        "title": "Voice Assistants Become Multilingual",
        "author": "Clara Nwosu",
        "facebook_link": "",
        "twitter_link": "https://twitter.com/voice-news",
        "linkedin_link": "",
        "content": "New AI models enable real-time multilingual conversation with virtual assistants.",
        "status": "inprogress",
    },
    {
        "title": "Crowdsourced Science Projects Gain Traction",
        "author": "Derek Miles",
        "facebook_link": "https://facebook.com/citizen-science",
        "twitter_link": "",
        "linkedin_link": "https://linkedin.com/in/citizenlab",
        "content": "Public participation is helping drive innovation in environmental and health research.",
        "status": "published",
    }
]